export enum ErrorCode {
  /* PRISMA ERROR */
  PRISMA_EMAIL_CREATE_ERROR = 'MS_EMAIL_PRISMA_CREATE_EMAIL_ERROR',
  PRISMA_EMAIL_UPDATE_ERROR = 'MS_EMAIL_PRISMA_UPDATE_EMAIL_ERROR',

  /* TEMPLATE ERROR */
  TEMPLATE_NOT_FOUND = 'MS_EMAIL_TEMPLATE_NOT_FOUND',
  TEMPLATE_CANNOT_ACCESS = 'MS_EMAIL_TEMPLATE_CANNOT_ACCESS',
  TEMPLATE_UNKNOWN_ERROR = 'MS_EMAIL_TEMPLATE_UNKNOWN_ERROR',
  TEMPLATE_PATH_INVALID = 'MS_EMAIL_TEMPLATE_PATH_INVALID',

  /* EMAIL PROVIDER */
  PROVIDER_SENDING_FAILED = 'MS_EMAIL_PROVIDER_SENDING_FAILED',
  PROVIDER_AUTHENTICATION_FAILED = 'MS_EMAIL_PROVIDER_AUTHENTICATION_FAILED',
  PROVIDER_NOT_CONFIGURED = 'MS_EMAIL_PROVIDER_NOT_CONFIGURED',

  /* VALIDATION */
  INVALID_PAYLOAD = 'MS_EMAIL_INVALID_PAYLOAD',
  VALIDATION_ERROR = 'MS_EMAIL_VALIDATION_ERROR',

  /* RABBITMQ ERRORS */
  RABBITMQ_CONNECTION_FAILED = 'MS_EMAIL_RABBITMQ_CONNECTION_FAILED',
  RABBITMQ_CHANNEL_ERROR = 'MS_EMAIL_RABBITMQ_CHANNEL_ERROR',
  RABBITMQ_MESSAGE_PROCESSING_FAILED = 'MS_EMAIL_RABBITMQ_MESSAGE_PROCESSING_FAILED',

  /* UNKNOWN */
  UNKNOWN_ERROR = 'MS_EMAIL_UNKNOWN_ERROR',
}
